add PublishCompiledWorkunitByName and FindWorkUnitsByName
hpccsystems-solutions-lab/Useful_ECL pull request #2
Opened 2020-12-12 00:14 UTC by lilyclemson

FindWorkUnitsByName is a stand-alone function that replaces the code fetching complied workunits by name inside the RunCompiledWorkunitsByName and PublishCompiledWorkunitByName

2020-12-14 12:43 UTC, dcamper requested changes
Looks great!  A few minor formatting/typo changes.

2020-12-14 12:43 UTC, dcamper commented on WorkunitExec.ecl
> +     *                              compiled;
Minor: should be 'compiled' (with apostrophes).

2020-12-14 12:43 UTC, dcamper commented on WorkunitExec.ecl
> +     *                              jobName;OPTIONAL, defualts to thor cluster
Minor:

- Missing space after semicolon
- "defualts" misspelled
- 'thor' should have apostrophes

2020-12-14 12:43 UTC, dcamper commented on WorkunitExec.ecl
> +        queryResults := FindWorkunitsByName(jobName, 'compiled', espURL , 'thor',username, userPW,timeoutInSeconds );
Minor: Need spaces after commas.

2020-12-14 12:43 UTC, dcamper commented on WorkunitExec.ecl
> +     EXPORT PublishResultsLayout := RECORD
Formatting: Please vertically-align the XPATH field attribute (see RunResultsLayout as an example).

2020-12-14 12:43 UTC, dcamper commented on WorkunitExec.ecl
> +     *                              jobName;OPTIONAL, defualts to Roxie cluster
Minor:

- Missing space after semicolon
- "defualts" misspelled
- 'roxie' should have apostrophes and be all lowercase

2020-12-14 12:43 UTC, dcamper commented on WorkunitExec.ecl
> +     *                              jobName;OPTIONAL, defualts to Roxie cluster
Minor:

- Missing space after semicolon
- "defualts" misspelled
- 'roxie' should have apostrophes and be all lowercase

2020-12-14 12:43 UTC, dcamper commented on WorkunitExec.ecl
> +        queryResults := FindWorkunitsByName(jobName, 'compiled', espURL , clusterName,username, userPW,timeoutInSeconds );
Formatting: spaces after commas

2021-01-12 13:59 UTC, dcamper commented on WorkunitExec.ecl
> +                                    the compiled workunit with provided
Missing asterisk.

2021-01-16 15:54 UTC, lilyclemson commented
The requested changes are made. Please review. Thank you.

2021-01-19 12:24 UTC, dcamper approved these changes

2021-01-19 12:25 UTC, merged